### ISSUE TITLE
A problem about data preprocessing

### ISSUE THREAD

**Issue by ghost** [qolina/NNED#2]
Excuse me,I am just a beginner for ACE Event Extraction,Thank you for sharing your code.But I have some  problems about prepareDataSet_joint.py as follows:

1. what should I put in "dataDir",in your example,the directory is "../ni_data/EngMix/dev(train/test)/ ",according to the dataset of ACE2005,which type of file should I put in?
2. When I run your code,I find some problems about in the function "obtainAllEvents",in details,is "cPickle",I get the error message saying "cPickle.UnpicklingError invalid load key",does it has something to do with the input files?

Thank you ! and please forgive my poor English.

**Comment by qolina** [comment]
Thanks for attention.
1. data files in ../ni_data/EngMix/dev/ include all *sgm and *apf.xml of dev files. For example, CNN_IP_20030409.1600.02.sgm, CNN_IP_20030409.1600.02.apf.xml

2. you should get *.ee files first with eventExtFromRaw.py.  For example, CNN_IP_20030409.1600.02.ee  

Good luck.

**Comment by ghost** [comment]
Thank you so much,I will have a try.

**Comment by ghost** [comment]
Sorry,Can I ask you for the ACE2005 original dataset？I just cannot find the corpus on the net.
Now I just have files end with ".sgm" and ".sgm.apf.xml"

**Comment by qolina** [comment]
Sorry about this. We could not release original dataset due to copyright issue.
".sgm" may be same with us. I am not sure about ".sgm.apf.xml". You may try change ".apf.xml" to ".sgm.apf.xml" in the code.

By the way, mine dataset is also slightly different with dataset provided by some collaborators. Not sure how many version there are..

**Comment by ghost** [comment]
Thank you ! The dataset on the LDC really costs too much.
