### ISSUE TITLE
Question about position feature(PF)

### ISSUE THREAD

**Issue by ghost** [qolina/NNED#3]
Hello,I have a question about PF.

In paper 'A Language-Independent Neural Network for Event Detection',the PF is described as "which is defined as the relative distance between the current word and the trigger candidate".

For example,a sentence which contains three words"w1,w2,w3",and w2 is the trigger candidate,so the PF to each word is -1 ,0 ,-1 .

But the function `position_fea_in_sent` confused me,I do not know why use` for loop`  and concat every embed in the function `forward`.
Thank you.

**Comment by qolina** [comment]
Hi, 
As you know, pf is the relative distance between current word and trigger candidate.

1. PF can not be negative like what you said, it is a distance. In your example, when w2 is trigger candidate, then pf of each word should be (1, 0, 1).

2. For one trigger candidate in one sentence, in your example, the PF is (1,0, 1). 
For all trigger candidates (w1, w2, and w3, respectively) in the sentence, PFs should be [(0, 1, 2), (1, 0, 1), (2, 1, 0)].

And I am dealing with a batch, containing batch_size sentences with max_length to be sent_length. the function position_fea_in_sent creates a PF vector for a batch.

**Comment by ghost** [comment]
Thank you!
