### ISSUE TITLE
About PRF

### ISSUE THREAD

**Issue by ghost** [qolina/NNED#4]
I'm sorry to bother you again and again.
I have a question about the calculation of prf for event detection.
1. In your code ,'none' is also an event type,so the prediction from 'none' to 'none' is also a correct tag.Use this evaluation,I get F score about 97%(maybe cause of my code bugs......)
2. Should we take the 'none' to 'none' in consider? This confused me.

Thank you!

**Comment by qolina** [comment]
The type 'None' should not be counted for evaluation.

**Comment by ghost** [comment]
thank you
